services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DB_HOST=postgres
      - DB_NAME=testdb
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_PORT=5432
    volumes:
      - .:/app
      - allure_results:/app/allure-results
    command: |
      sh -c "
        echo 'Установка зависимостей...'
        pip install -r requirements.txt &&
        echo 'Запуск тестов...'
        pytest --alluredir=/app/allure-results --disable-warnings && tail -f /dev/null
      "

volumes:
  postgres_data:
  allure_results:
