pipeline {
    agent {
        docker {
            image 'python:3.9'
            args '-u root'
        }
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
                git 'https://github.com/Gimeshli-Andrey/Homework.AQA.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                sh '''
                    python -m pip install --upgrade pip
                    pip install -r requirements.txt
                '''
            }
        }

        stage('Run Tests') {
            steps {
                script {
                    try {
                        sh 'python -m pytest --alluredir=allure-results --disable-warnings'
                    } catch (Exception e) {
                        currentBuild.result = 'FAILURE'
                        throw e
                    }
                }
            }
        }

        stage('Publish Test Results') {
            steps {
                allure([
                    includeProperties: false,
                    jdk: '',
                    properties: [],
                    reportBuildPolicy: 'ALWAYS',
                    results: [[path: 'allure-results']]
                ])
            }
        }
    }

    post {
        always {
            emailext (
                to: 'InsertYour@Mail.Here',
                subject: "${currentBuild.currentResult}: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]'",
                body: """
                    <p>Статус збірки: ${currentBuild.currentResult}</p>
                    <p>Номер збірки: ${env.BUILD_NUMBER}</p>
                    <p>Переглянути лог збірки: <a href='${env.BUILD_URL}'>${env.JOB_NAME} [${env.BUILD_NUMBER}]</a></p>
                    <p>Звіт тестування Allure: <a href='${env.BUILD_URL}allure'>Allure Report</a></p>
                """,
                mimeType: 'text/html',
                attachLog: true
            )
        }

        cleanup {
            cleanWs()
        }
    }
}
