services:
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    container_name: jenkins
    volumes:
      - /Users/gimeshli.a/Desktop/Homework.AQA/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./31.homework:/workspace/31.homework
    environment:
      - JAVA_OPTS="-Djenkins.install.runSetupWizard=false"
    restart: always